### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by GaryJones**
`wich` -> `which`

### CODE REVIEW

**Comment by zeldman** [comment]
Hi, folks. I did not subscribe to this stream (as I did not know about it, as I'm not involved in this project). Am wondering how I got subscribed to it. I keep unsubscribing when I receive a new notification (which is meaningless to me as I'm not involved in this), yet I keep receiving updates to the thread. What's up? P.S. friendly wave to @kristastevens Miss you, girl!

**Comment by michaelbeil** [comment]
be sure to click `unwatch` and then select `not watching` up top, and you should be unsubcribed: http://beil.io/15xGg

**Comment by kristastevens** [comment]
Friendly wave to @zeldman! Hope you're well and sorry about that chief! Not sure how you became subscribed to this. "Unwatch" and we should be outta your hair for good.

**Comment by zeldman** [comment]
Thanks, @michaelbeil and @kristastevens . Duh, yup. Did that shortly after leaving my comment and it seems to have taken care of things. Still puzzled as to exactly how I got added to the thread, though. Oh, well. Kismet. Good luck with your projects. :)

**Pull request merged**
